services:
  db-pdfencryptor:
    image: 'postgres:16'
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - 'POSTGRES_DB=pdfencryptordb'
      - 'POSTGRES_USER=pdfencryptor'
      - 'POSTGRES_PASSWORD=PNSJkxXvVNDAhePMuExTBuRR'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - '$PWD/db-pdfencryptor:/var/lib/postgresql/data'
    ports:
      - '5432:5432'